version: '1.0.0'

volumes:
  postgres-data:

services:
  backend:
    container_name: desafio-${BACKEND_CONTAINER_NAME}
    build:
      context: ./.docker/backend
      dockerfile: Dockerfile
    environment:
      BACKEND_DATABASE_PASSWORD: ${BACKEND_DATABASE_PASSWORD}
      BACKEND_DATABASE_USER: ${BACKEND_DATABASE_USER}
      BACKEND_DATABASE_DB: ${BACKEND_DATABASE_DB}
      BACKEND_DATABASE_HOSTNAME: ${BACKEND_DATABASE_HOSTNAME}
      BACKEND_DATABASE_PORT: ${BACKEND_DATABASE_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      - .:/workspaces:cached
      - .:/app
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db

  db:
    container_name: desafio-${DATABASE_CONTAINER_NAME}
    command: -p ${DATABASE_PORT}
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
      args:
        BACKEND_DATABASE_PASSWORD: ${BACKEND_DATABASE_PASSWORD}
        BACKEND_DATABASE_USER: ${BACKEND_DATABASE_USER}
        BACKEND_DATABASE_DB: ${BACKEND_DATABASE_DB}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

    # Add "forwardPorts": ["5433"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
